import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users/index";
import liveRouter from "./live";
import historyRouter from "./history";
import dayplanRouter from "./dayplan";
import publicRouter from "./public";
import onboardingRouter from "./onboarding";
import ingestRouter from "./ingest";
import simulatorRouter from "./simulator";
import dispositionsRouter from "./dispositions";
import configRouter from "./config";
import mobileAuthRouter from "./mobileAuth";
import mobileStatusRouter from "./mobileStatus";
import devicesRouter from "./devices";
import vendorAccountsRouter from "./vendorAccounts";
import deviceCategoriesRouter from "./deviceCategories";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(liveRouter);
router.use(historyRouter);
router.use(dayplanRouter);
router.use(publicRouter);
router.use(onboardingRouter);
router.use(ingestRouter);
router.use(simulatorRouter);
router.use(dispositionsRouter);
router.use(configRouter);
router.use(mobileAuthRouter);
router.use(mobileStatusRouter);
router.use(devicesRouter);
router.use(vendorAccountsRouter);
router.use(deviceCategoriesRouter);

export default router;
